version: '3.8'

services:

  bot:
    build:
      context: ./app/
    container_name: bot
    command: ['sh', 'start-work.sh']
    volumes:
      - ./app/:/app
    ports:
      - "5000:5000"
    env_file:
      - ./app/.env
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - app/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - /app/.env
    ports:
      - 8001:80
    depends_on:
      - db
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network: